# Generated by Django 3.0.8 on 2020-08-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
