# Generated by Django 3.0.8 on 2020-08-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0005_contactformmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormMessage',
        ),
    ]
